#ifndef CC1101CFG_H
#define CC1101CFG_H

#include "CC1101.h"
#include <avr/pgmspace.h>

#define CC1101_NR_OF_REGISTERS 35
// list the registers in the same order as CC1101RegisterSettings
// stored in progmem to save on RAM
static const byte CC1101_registers[CC1101_NR_OF_REGISTERS] PROGMEM =
{
	CC1101_FSCTRL1	,
	CC1101_FSCTRL0	,
	CC1101_FREQ2	,
	CC1101_FREQ1	,
	CC1101_FREQ0	,
	CC1101_MDMCFG4	,
	CC1101_MDMCFG3	,
	CC1101_MDMCFG2	,
	CC1101_MDMCFG1	,
	CC1101_MDMCFG0	,
	CC1101_CHANNR	,
	CC1101_DEVIATN	,
	CC1101_FREND1	,
	CC1101_FREND0	,
	CC1101_MCSM0	,
	CC1101_FOCCFG	,
	CC1101_BSCFG	,
	CC1101_AGCCTRL2	,
	CC1101_AGCCTRL1	,
	CC1101_AGCCTRL0	,
	CC1101_FSCAL3	,
	CC1101_FSCAL2	,
	CC1101_FSCAL1	,
	CC1101_FSCAL0	,
	CC1101_FSTEST	,
	CC1101_TEST2	,
	CC1101_TEST1	,
	CC1101_TEST0	,
	CC1101_FIFOTHR	,
	CC1101_IOCFG2	,
	CC1101_IOCFG0D	,
	CC1101_PKTCTRL1	,
	CC1101_PKTCTRL0	,
	CC1101_ADDR	,
	CC1101_PKTLEN	,
};

// configuration for CC1101 generated by TI's SmartRf studio
// stored in progmem to save on RAM
static const byte CC1101_registerSettings[CC1101_NR_OF_REGISTERS] PROGMEM = 
{
	0x08,   // FSCTRL1   Frequency synthesizer control.
	0x00,   // FSCTRL0   Frequency synthesizer control.
	0x23,   // FREQ2     Frequency control word, high byte.
	0x31,   // FREQ1     Frequency control word, middle byte.
	0x3B,   // FREQ0     Frequency control word, low byte.
	0x7B,   // MDMCFG4   Modem configuration.
	0x83,   // MDMCFG3   Modem configuration.
	0x03,   // MDMCFG2   Modem configuration.
	0x22,   // MDMCFG1   Modem configuration.
	0xF8,   // MDMCFG0   Modem configuration.
	0x00,   // CHANNR    Channel number.
	0x42,   // DEVIATN   Modem deviation setting (when FSK modulation is enabled).
	0xB6,   // FREND1    Front end RX configuration.
	0x10,   // FREND0    Front end TX configuration.
	0x18,   // MCSM0     Main Radio Control State Machine configuration.
	0x1D,   // FOCCFG    Frequency Offset Compensation Configuration.
	0x1C,   // BSCFG     Bit synchronization Configuration.
	0xC7,   // AGCCTRL2  AGC control.
	0x00,   // AGCCTRL1  AGC control.
	0xB2,   // AGCCTRL0  AGC control.
	0xEA,   // FSCAL3    Frequency synthesizer calibration.
	0x2A,   // FSCAL2    Frequency synthesizer calibration.
	0x00,   // FSCAL1    Frequency synthesizer calibration.
	0x1F,   // FSCAL0    Frequency synthesizer calibration.
	0x59,   // FSTEST    Frequency synthesizer calibration.
	0x81,   // TEST2     Various test settings.
	0x35,   // TEST1     Various test settings.
	0x09,   // TEST0     Various test settings.
	0x0E,   // FIFOTHR   RXFIFO and TXFIFO thresholds.
	0x09,   // IOCFG2    GDO2 output pin configuration.0x09-CCA mode, 0x2E-High impedance
	0x01,   // IOCFG0D   GDO0 output pin configuration. Refer to SmartRF?Studio User Manual for detailed pseudo register explanation.
	0x04,   // PKTCTRL1  Packet automation control. bit2 = 1 append RSSI and LQI ,bit2 = 0 not append
	0x05,   // PKTCTRL0  Packet automation control.
	0x00,   // ADDR      Device address.
	CC1101_PACKT_LEN,    // PKTLEN    Packet length.
};